
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'IDENTIFIER LBRACE LPAREN NUMBER RBRACE RESERVED RPAREN SEMICOLONfunction : RESERVED RESERVED LPAREN RPAREN LBRACE block RBRACEblock : statement block\n             | statementstatement : RESERVED IDENTIFIER SEMICOLON'
    
_lr_action_items = {'RESERVED':([0,2,6,9,13,],[2,3,7,7,-4,]),'$end':([1,11,],[0,-1,]),'LPAREN':([3,],[4,]),'RPAREN':([4,],[5,]),'LBRACE':([5,],[6,]),'IDENTIFIER':([7,],[10,]),'RBRACE':([8,9,12,13,],[11,-3,-2,-4,]),'SEMICOLON':([10,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,],[1,]),'block':([6,9,],[8,12,]),'statement':([6,9,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('function -> RESERVED RESERVED LPAREN RPAREN LBRACE block RBRACE','function',7,'p_function','app.py',58),
  ('block -> statement block','block',2,'p_block','app.py',63),
  ('block -> statement','block',1,'p_block','app.py',64),
  ('statement -> RESERVED IDENTIFIER SEMICOLON','statement',3,'p_statement_declaration','app.py',72),
]
